import request from '../lib/request';

const Disclaimer = (props:any) => {
    const {page} = props;
    const disclaimer = page.disclaimer;
    return (
      <>
        {/* <Head>
          <title>Terms And Condition</title>
          <meta name="Description" content="Generated by create your app"></meta>
          <link rel='icon' href="/Logo.png"></link>
        </Head> */}
        <div style={{marginTop: '60px', minHeight: '600px',padding:'20px'}} dangerouslySetInnerHTML={{__html: disclaimer}}>
   
        </div>
        </>
    );
};

export default Disclaimer;
 

export async function getServerSideProps(context:any) {
  
    const page = await request(`disclaimer-info`,'');
  
  
  
    return {
      props: {
        page: page?.data[0],
        // fallback: false,
      }
    }
  }