import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Online Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home__container}>
        <div className={styles.video__overlay}></div>
        <video src={'/assets/videos/gaming.webm'} autoPlay loop muted />
        <div className={styles.video__content}>
          <h1>GET PAID TO <span className={styles.video__content__play}>PLAY</span></h1>
          <div style={{textAlign: 'center', marginTop: '15px'}}>
            <p style={{marginBottom: '0px'}}>Compete in Free and Paid entry Tournaments in just a</p>
            <p>few clicks without any additional downloads</p>
          </div>
          <div className={styles.counter__container}>
            <div>
              <p>Games Played on Repeat</p>
              <h5>260,828,947</h5>
            </div>
            <div>
              <p>Total Prizes Paid Out</p>
              <h5><span>$</span>986,843</h5>
            </div>
          </div>
        </div>
      </div>
      <Container>
        <div className={styles.games__container}>
          <h3>Available Games</h3>
          <p>We are constantly adding new games</p>
          <div style={{position: 'absolute', right: '10px', marginTop: '-140px', backgroundColor: '#00ACF6', color: 'white', padding: '8px 30px', cursor: 'pointer'}}>
            <a>
              <p style={{marginBottom: '0px'}}>Start playing Now!</p>
              <h6 style={{fontSize: '19px'}}>Create Account</h6>
            </a>
          </div>
          <div className={styles.games__grid__view}>
            <div>
              <Image src={`/assets/images/game/1b.jpg`} height={350} width={230} style={{borderBottomRightRadius: '35px'}} />
            </div>
            <div>
              <Image src={`/assets/images/game/2b.jpg`} height={350} width={230}  style={{borderBottomRightRadius: '35px'}} />
            </div>
            <div>
              <Image src={`/assets/images/game/3b.jpg`} height={350} width={230}  style={{borderBottomRightRadius: '35px'}} />
            </div>
            <div>
              <Image src={`/assets/images/game/4b.jpg`} height={350} width={230}  style={{borderBottomRightRadius: '35px'}} />
            </div>
            <div>
              <Image src={`/assets/images/game/5b.jpg`} height={350} width={230}  style={{borderBottomRightRadius: '35px'}} />
            </div>
          </div>
        </div>
      </Container>
    </div>
  )
}

export default Home
