import { Container } from "react-bootstrap";
import request from "../lib/request";

const TermsAndConditions = (props: any) => {
  const { page } = props;
  const termsAndCondition = page.termsCondition;
  return (
    <>
      {/* <Head>
          <title>Terms And Condition</title>
          <meta name="Description" content="Generated by create your app"></meta>
          <link rel='icon' href="/Logo.png"></link>
        </Head> */}
      {/* <div style={{marginTop: '60px', minHeight: '600px',padding:'20px'}} dangerouslySetInnerHTML={{__html: termsAndCondition}}>
   
        </div> */}
      <Container>
        <div
          style={{
            marginTop: "60px",
            minHeight: "600px",
            padding: "20px",
          }}
        >
          <h5 style={{ fontWeight: "bold" }}>
            The Ultimate Players Arena Affiliate Program Agreement
          </h5>
          <p>
            This agreement describes the terms and conditions for participation
            in The Ultimate Players Arena Affiliate Program. The terms
            "Affiliate," "You," and "Your" are referring to you, the applicant.
            "We”, “UPA”, The Company”, and "Our" refer to The Ultimate Players
            Arena. We are independent parties and this agreement will not form
            any partnership.
          </p>
          <h5 style={{ fontWeight: "bold" }}>AGREEMENT DURATION</h5>
          <p>
            This agreement will begin upon our acceptance of your affiliate
            application and will end when terminated by either party.
            Termination may happen at any time, with or without cause, by giving
            the other party written notice of termination.
          </p>
          <h5 style={{ fontWeight: "bold" }}>UPDATES AND MODIFICATIONS</h5>
          <p>
            By posting an Update Notice or a new agreement on this site, we may
            modify any of the terms and conditions within this Agreement at any
            time and at our sole discretion. These modifications may include,
            but not limited to changes in the scope of available referral fees,
            fee schedules, payment procedures, and Program rules. If any of the
            modifications are UNACCEPTABLE TO YOU, your only recourse is to
            terminate this Agreement. If you CONTINUE PARTICIPATION IN THE
            PROGRAM following the posting of an Update Notice or new agreement,
            it will be considered as your acceptance of the change.
          </p>
          <h5 style={{ fontWeight: "bold" }}>COMMISSION FEES</h5>
          <p>
            You will receive CAD 10 per new depositing member as a commission
            for traffic directed from your Affiliate activities to The Ultimate
            Players Arena. For a depositing member to generate a commission for
            an Affiliate (Qualified Commission), the depositing member must
            deposit with seven (7) days of registration and remain a member in
            good standing. To be considered a member in good standing, the
            depositing member must have a turnover of at least CAD 20 within a
            period of thirty (30) days after they made the initial deposit. If
            the referred member loses their initial deposit before reaching the
            specified turnover, without requesting any withdrawals, they will be
            considered as a member in good standing as well. Affiliate
            commissions will only be paid for depositors which are made through
            qualified Affiliate links.
          </p>
          <p>
            Qualified Commissions can only be earned between the acceptance of
            the Affiliate application and notice of termination.
          </p>
          <p>
            Qualified commissions are paid on a monthly basis and will be paid
            on the 7th day following the end of the calendar month by UPA. There
            is a CAD 50 threshold for issuing a payment. If the CAD 50 threshold
            is not met within a given month the amount owed by UPA to the
            Affiliate will be applied towards the next month.
          </p>
          <p>
            Any returned deposits, chargebacks, or fees from a depositor
            referred by the Affiliate will be adjusted in the following
            commission payment.
          </p>
          <h5 style={{ fontWeight: "bold" }}>WEBSITE RESTRICTIONS</h5>
          <p>
            UPA reserves the right not to accept any site into the UPA affiliate
            program for any reason. SPAM (UCE) Unsolicited Commercial E-mail -
            upaesports.com in no way participates in mass unsolicited e-mailing
            (i.e. spamming), and all Affiliates are expected to adhere to this
            policy as well. Violation of this policy will result in the
            termination of this contract and immediate dismissal from The
            Ultimate Players Arena Affiliate Program, any outstanding balance
            due to the Affiliate will be revoked.
          </p>
          <h5 style={{ fontWeight: "bold" }}>DISCLAIMER</h5>
          <p>
            We make no express or implied warranties or representations with
            respect to the Affiliate Program or your potential to earn income
            from the Ultimate Players Arena Affiliate Program. In addition, we
            make no representation that the operation of our site or the
            Affiliate Sites will be uninterrupted or error-free, and we will not
            be liable for the consequences of any interruptions or downtime.
            This Agreement will be governed by the laws of Canada and the
            Province of British Columbia, without reference to rules governing
            choice of laws. Any action relating to this Agreement must be
            brought in the Federal or Provincial courts located in British
            Columbia, and you irrevocably consent to the jurisdiction of such
            courts. You may not assign this Agreement, by operation of law or
            otherwise, without our prior written consent. Subject to that
            restriction, this Agreement will be binding on, inure to the benefit
            of, and enforceable against the parties and their respective
            successors and assigns. Our failure to enforce your strict
            performance of any provision of this Agreement will not constitute a
            waiver of our right to subsequently enforce such provision or any
            other provision of this Agreement.
          </p>
          <p>
            By submitting this Affiliate Agreement form, you acknowledge that
            you have read this agreement and agree to all its terms and
            conditions. You have independently evaluated this program and are
            not relying on any representation, guarantee, or statement other
            than as set forth in this agreement.
          </p>
        </div>
      </Container>
    </>
  );
};

export default TermsAndConditions;

export async function getServerSideProps(context: any) {
  const page = await request(`terms-condition`, "");

  return {
    props: {
      page: page?.data[0],
      // fallback: false,
    },
  };
}
